/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class FrmCliente extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    public FrmCliente() {
        initComponents();
         jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jCheckBoxExibeOpcoesAdmin.setEnabled(false);
        jLabelPercent.setVisible(false);
        jLabelSimboloPercent.setVisible(false);
        jTextFieldPercent.setVisible(false);
        jDateChooserClienteDesde.setEnabled(false);

        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonSalvarEdicoes.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        conecta.conexao();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelClienteDesde = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabelSimboloPercent = new javax.swing.JLabel();
        jLabelPercent = new javax.swing.JLabel();
        jCheckBoxExibeOpcoesAdmin = new javax.swing.JCheckBox();
        jTextFieldNomeCliente = new javax.swing.JTextField();
        jTextFieldPercent = new javax.swing.JTextField();
        jTextFieldTelefoneCliente = new javax.swing.JTextField();
        jTextFieldCodCliente = new javax.swing.JTextField();
        jTextFieldEnderecoCliente = new javax.swing.JTextField();
        jButtonSair = new javax.swing.JButton();
        jDateChooserClienteDesde = new com.toedter.calendar.JDateChooser();
        jButtonCadastrarCliente = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jButtonNovoCliente = new javax.swing.JButton();
        jButtonEditarDados = new javax.swing.JButton();
        jButtonExcluirCliente = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jButtonCancelar = new javax.swing.JButton();
        jButtonSalvarEdicoes = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));

        jLabelClienteDesde.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N

        jLabel2.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel2.setText("Cadastro de Clientes");

        jLabel3.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel3.setText("Telefone:");

        jLabel4.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel4.setText("Endereço:");

        jLabel6.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel6.setText("Nome:");

        jLabel5.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel5.setText("Cliente desde:");

        jLabelSimboloPercent.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabelSimboloPercent.setText("%");

        jLabelPercent.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabelPercent.setText("Percentual de acréscimo:");

        jCheckBoxExibeOpcoesAdmin.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jCheckBoxExibeOpcoesAdmin.setText("Exibir opções do administrador");
        jCheckBoxExibeOpcoesAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxExibeOpcoesAdminActionPerformed(evt);
            }
        });

        jTextFieldNomeCliente.setFont(new java.awt.Font("SFNS Display", 1, 24)); // NOI18N

        jTextFieldPercent.setFont(new java.awt.Font("SFNS Display", 1, 24)); // NOI18N
        jTextFieldPercent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPercentActionPerformed(evt);
            }
        });

        jTextFieldTelefoneCliente.setFont(new java.awt.Font("SFNS Display", 1, 24)); // NOI18N
        jTextFieldTelefoneCliente.setText("(085)");
        jTextFieldTelefoneCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldTelefoneClienteActionPerformed(evt);
            }
        });

        jTextFieldCodCliente.setFont(new java.awt.Font("SFNS Display", 1, 24)); // NOI18N
        jTextFieldCodCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodClienteKeyPressed(evt);
            }
        });

        jTextFieldEnderecoCliente.setFont(new java.awt.Font("SFNS Display", 1, 24)); // NOI18N

        jButtonSair.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonSair.setText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jButtonCadastrarCliente.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonCadastrarCliente.setText("Salvar Dados");
        jButtonCadastrarCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarClienteActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_lollypop-lollipop.png"))); // NOI18N
        jLabel7.setText("G20PDV");

        jButtonNovoCliente.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonNovoCliente.setText("Novo Cliente");
        jButtonNovoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoClienteActionPerformed(evt);
            }
        });

        jButtonEditarDados.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonEditarDados.setText("Editar Dados");
        jButtonEditarDados.setEnabled(false);
        jButtonEditarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarDadosActionPerformed(evt);
            }
        });

        jButtonExcluirCliente.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonExcluirCliente.setText("Excluir Cliente");
        jButtonExcluirCliente.setEnabled(false);
        jButtonExcluirCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirClienteActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SFNS Display", 1, 30)); // NOI18N
        jLabel11.setText("Código:");

        jButtonCancelar.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });

        jButtonSalvarEdicoes.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jButtonSalvarEdicoes.setText("Salvar Edições");
        jButtonSalvarEdicoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarEdicoesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel6)
                            .addComponent(jLabel11))
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 966, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 720, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jCheckBoxExibeOpcoesAdmin)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooserClienteDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(52, 52, 52)
                                .addComponent(jLabelClienteDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelPercent)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPercent, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelSimboloPercent))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovoCliente)
                        .addGap(66, 66, 66)
                        .addComponent(jButtonCadastrarCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditarDados, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvarEdicoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExcluirCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(194, 194, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(22, 22, 22))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                    .addContainerGap(499, Short.MAX_VALUE)
                    .addComponent(jLabel2)
                    .addGap(484, 484, 484)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(56, 56, 56))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldCodCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextFieldNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldEnderecoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(55, 55, 55)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jTextFieldTelefoneCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooserClienteDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabelClienteDesde, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(35, 35, 35)
                .addComponent(jCheckBoxExibeOpcoesAdmin)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPercent)
                    .addComponent(jLabelSimboloPercent)
                    .addComponent(jTextFieldPercent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEditarDados)
                    .addComponent(jButtonNovoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonExcluirCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCadastrarCliente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonSalvarEdicoes, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(91, 91, 91))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(21, 21, 21)
                    .addComponent(jLabel2)
                    .addContainerGap(711, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPercentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPercentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPercentActionPerformed

    private void jCheckBoxExibeOpcoesAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxExibeOpcoesAdminActionPerformed
     if(jCheckBoxExibeOpcoesAdmin.isSelected()){
         jLabelPercent.setVisible(true);
         jTextFieldPercent.setVisible(true);
         jLabelSimboloPercent.setVisible(true);
         
     }else{
        jLabelPercent.setVisible(false);
         jTextFieldPercent.setVisible(false);
         jLabelSimboloPercent.setVisible(false); 
     }         
    }//GEN-LAST:event_jCheckBoxExibeOpcoesAdminActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
    
        dispose();
        
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jTextFieldTelefoneClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldTelefoneClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldTelefoneClienteActionPerformed

    private void jButtonCadastrarClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarClienteActionPerformed
       try {
            Date d = jDateChooserClienteDesde.getDate();
            java.sql.Date dataSql = new java.sql.Date(d.getTime());
           
            
            PreparedStatement pst = conecta.conn.prepareStatement("INSERT INTO cliente (nome, codigo_cliente, endereco, telefone, cliente_desde, percentual_acrescimo)values(?,?,?,?,?,?)"); //passagem do sql a ser executado
            pst.setString(1, (jTextFieldNomeCliente.getText()));
            pst.setString(2, jTextFieldCodCliente.getText());// passagem dos parametros
            pst.setString(3, jTextFieldEnderecoCliente.getText());
            pst.setString(4, jTextFieldTelefoneCliente.getText());
            pst.setDate(5, dataSql);
            pst.setDouble(6, Double.parseDouble(jTextFieldPercent.getText()));
           
          
            pst.executeUpdate(); //chamado do metodo para executar a instrucao
           
            JOptionPane.showMessageDialog(rootPane, "Clente cadastrado com sucesso!");
            //preencherTabela("SELECT * FROM produto ORDER BY procod");
                    // TODO add your handling code here:
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar \n Erro: " + ex);
        }
        
       
        jTextFieldNomeCliente.setText("");
        jTextFieldCodCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
        jTextFieldPercent.setText("");
        
        
        jCheckBoxExibeOpcoesAdmin.setSelected(false);
      
        
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldNomeCliente.setEnabled(false);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jTextFieldPercent.setEnabled(false);
       
        jCheckBoxExibeOpcoesAdmin.setEnabled(false);
        jDateChooserClienteDesde.setEnabled(false);
        
        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonSair.setEnabled(true);
    }//GEN-LAST:event_jButtonCadastrarClienteActionPerformed

    private void jButtonNovoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoClienteActionPerformed

        
        jTextFieldNomeCliente.setText("");
        jTextFieldCodCliente.setText("");
        jTextFieldEnderecoCliente.setText("");
        jTextFieldTelefoneCliente.setText("");
        jCheckBoxExibeOpcoesAdmin.setSelected(false);
      
        jTextFieldPercent.setText("");
        
        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(true);
        jTextFieldTelefoneCliente.setEnabled(true);
        jCheckBoxExibeOpcoesAdmin.setEnabled(true);
        
        jTextFieldPercent.setEnabled(true);
        jDateChooserClienteDesde.setEnabled(true);

        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(true);
        jButtonNovoCliente.setEnabled(false);
        jButtonSair.setEnabled(true);

    }//GEN-LAST:event_jButtonNovoClienteActionPerformed

    private void jButtonEditarDadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarDadosActionPerformed

        jTextFieldNomeCliente.setEnabled(true);
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(true);
        jTextFieldTelefoneCliente.setEnabled(true);
        jCheckBoxExibeOpcoesAdmin.setEnabled(true);
        
        jTextFieldPercent.setEnabled(true);
        jDateChooserClienteDesde.setEnabled(true);
        
        jButtonNovoCliente.setEnabled(false);
        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(false);
        jButtonSalvarEdicoes.setEnabled(true);

    }//GEN-LAST:event_jButtonEditarDadosActionPerformed

    private void jButtonExcluirClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirClienteActionPerformed

    private void jTextFieldCodClienteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodClienteKeyPressed
            if(evt.getKeyCode() == KeyEvent.VK_ENTER){
          
             conecta.executaSQL("SELECT * FROM cliente WHERE codigo_cliente='" + jTextFieldCodCliente.getText()+"'" );
             try {
                 if(conecta.rs.next()){
                     jTextFieldNomeCliente.setText(conecta.rs.getString("nome"));
                     jTextFieldCodCliente.setText(conecta.rs.getString("codigo_cliente"));
                     jTextFieldEnderecoCliente.setText(conecta.rs.getString("endereco"));
                     jTextFieldTelefoneCliente.setText(conecta.rs.getString("telefone"));
                     jLabelClienteDesde.setText(conecta.rs.getString("cliente_desde"));
                     jTextFieldPercent.setText(conecta.rs.getString("percentual_acrescimo"));
                     
                     
                     jButtonNovoCliente.setEnabled(true);
                     jButtonEditarDados.setEnabled(true);
                     jButtonExcluirCliente.setEnabled(true);
                     jButtonCadastrarCliente.setEnabled(false);
                     jButtonSair.setEnabled(true);
                     jButtonCancelar.setEnabled(true);
                     
                     
                     
                 }
             } catch (SQLException ex) {
                 JOptionPane.showMessageDialog(rootPane,"Erro ao pesquisar cliente ou cliente não cadastrado!  " + ex);
             }
             
             
         }
        
    }//GEN-LAST:event_jTextFieldCodClienteKeyPressed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
          jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jCheckBoxExibeOpcoesAdmin.setEnabled(false);
        jLabelPercent.setVisible(false);
        jLabelSimboloPercent.setVisible(false);
        jTextFieldPercent.setVisible(false);
        jDateChooserClienteDesde.setEnabled(false);

        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonSalvarEdicoes.setEnabled(false);
        jButtonCancelar.setEnabled(false);
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarEdicoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarEdicoesActionPerformed
             PreparedStatement pst;
             Date d = jDateChooserClienteDesde.getDate();
            java.sql.Date dataSql = new java.sql.Date(d.getTime());
        try {
            pst = conecta.conn.prepareStatement("UPDATE cliente SET nome=?, codigo_cliente=?, endereco=?, telefone=?, cliente_desde=?, percentual_acrescimo=? where codigo_cliente=? "); //passagem do sql a ser executado
            pst.setString(1, (jTextFieldNomeCliente.getText()));
            pst.setString(2, jTextFieldCodCliente.getText());// passagem dos parametros
            pst.setString(3, jTextFieldEnderecoCliente.getText());
            pst.setString(4, jTextFieldTelefoneCliente.getText());
            pst.setDate(5, dataSql);
            pst.setDouble(6, Double.parseDouble(jTextFieldPercent.getText()));
            pst.setString(7, jTextFieldCodCliente.getText());
            pst.executeUpdate();
             JOptionPane.showMessageDialog(rootPane, "Dados editados com sucesso!");
             
             
             jTextFieldNomeCliente.setEnabled(false);
        jTextFieldCodCliente.setEnabled(true);
        jTextFieldEnderecoCliente.setEnabled(false);
        jTextFieldTelefoneCliente.setEnabled(false);
        jCheckBoxExibeOpcoesAdmin.setEnabled(false);
        jLabelPercent.setVisible(false);
        jLabelSimboloPercent.setVisible(false);
        jTextFieldPercent.setVisible(false);
        jDateChooserClienteDesde.setEnabled(false);

        jButtonEditarDados.setEnabled(false);
        jButtonExcluirCliente.setEnabled(false);
        jButtonCadastrarCliente.setEnabled(false);
        jButtonNovoCliente.setEnabled(true);
        jButtonSair.setEnabled(true);
        jButtonSalvarEdicoes.setEnabled(false);
        jButtonCancelar.setEnabled(false);
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane,"Erro ao editar dados, segue erro: " + ex);
        }
            
           
          
            
    }//GEN-LAST:event_jButtonSalvarEdicoesActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarCliente;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonEditarDados;
    private javax.swing.JButton jButtonExcluirCliente;
    private javax.swing.JButton jButtonNovoCliente;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvarEdicoes;
    private javax.swing.JCheckBox jCheckBoxExibeOpcoesAdmin;
    private com.toedter.calendar.JDateChooser jDateChooserClienteDesde;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelClienteDesde;
    private javax.swing.JLabel jLabelPercent;
    private javax.swing.JLabel jLabelSimboloPercent;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodCliente;
    private javax.swing.JTextField jTextFieldEnderecoCliente;
    private javax.swing.JTextField jTextFieldNomeCliente;
    private javax.swing.JTextField jTextFieldPercent;
    private javax.swing.JTextField jTextFieldTelefoneCliente;
    // End of variables declaration//GEN-END:variables
}
