/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import utilitarios.ConectaBanco;
import utilitarios.ModeloTabela;

/**
 *
 * @author gabrielbastos
 */
public class FrmMesa extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco(); // Instancia da classe de conexao
    
    public FrmMesa() {
        initComponents();
        conecta.conexao(); // chamada do metodo de conexao
        //preencherTabela("SELECT * FROM MESA ORDER BY descricao_mesa limit 30");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodMesa = new javax.swing.JTextField();
        jTextFieldDescricaoMesa = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jButtonLimparCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Código:");

        jLabel3.setText("Descrição");

        jTextFieldCodMesa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCodMesa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodMesaKeyPressed(evt);
            }
        });

        jTextFieldDescricaoMesa.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldDescricaoMesa.setEnabled(false);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_199_CircledPlus_183316.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_081_Pen_183209.png"))); // NOI18N
        jButtonEditar.setText("Aplicar Edições");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_178_Download_183297.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_068_Cancel_183197.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_059_CircledOff_183188.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableEstado);

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_previous-2_293643.png"))); // NOI18N
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_next_293690.png"))); // NOI18N
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-right_293665.png"))); // NOI18N
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jButtonLimparCampos.setText("Cancelar");
        jButtonLimparCampos.setToolTipText("Novo");
        jButtonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCodMesa)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextFieldDescricaoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonLimparCampos)
                                .addGap(32, 32, 32)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCodMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldDescricaoMesa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimparCampos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo)
                        .addComponent(jButtonEditar)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonExcluir))
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Mesas");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_lollypop-lollipop.png"))); // NOI18N
        jLabel9.setText("G20PDV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        setSize(new java.awt.Dimension(892, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("INSERT INTO mesa (cod_mesa, descricao_mesa)values(?,?)"); //passagem do sql a ser executado
            pst.setInt(1, Integer.parseInt(jTextFieldCodMesa.getText()));
            pst.setString(2, jTextFieldDescricaoMesa.getText());// passagem dos parametros
            
            
            pst.executeUpdate(); //chamado do metodo para executar a instrucao
           
            JOptionPane.showMessageDialog(rootPane, "Registro Salvo!");
            //preencherTabela("SELECT * FROM MESA ORDER BY DESCRICAO_MESA");
                    // TODO add your handling code here:
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar \n Erro: " + ex);
        }
        
        jTextFieldCodMesa.setText("");
        jTextFieldDescricaoMesa.setText("");
        
        jTextFieldDescricaoMesa.setEnabled(false);
        
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
                conecta.executaSQL("DELETE FROM produto WHERE COD_MESA='"+jTextFieldCodMesa.getText()+"'");//chama metodo da classe ConectaBanco para exclusao
             JOptionPane.showMessageDialog(null, "Registro de PRODUTO excluído com sucesso!");
             
            jTextFieldCodMesa.setText("");
            jTextFieldDescricaoMesa.setText("");
        
        jTextFieldCodMesa.setEnabled(true);
        jTextFieldDescricaoMesa.setEnabled(true);
        
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        
        jTextFieldDescricaoMesa.setText("");
        
        jTextFieldCodMesa.setEnabled(true);
        jTextFieldDescricaoMesa.setEnabled(true);
        
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        try{
            
            conecta.executaSQL("SELECT * FROM MESA");
            conecta.rs.first();
            jTextFieldCodMesa.setText(conecta.rs.getString("COD_MESA"));
            jTextFieldDescricaoMesa.setText(conecta.rs.getString("DESCRICAO_MESA"));
            
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldDescricaoMesa.setEnabled(true);
          
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        try{
            
            conecta.executaSQL("SELECT * FROM MESA");
            conecta.rs.last();
            jTextFieldCodMesa.setText(conecta.rs.getString("COD_MESA"));
            jTextFieldDescricaoMesa.setText(conecta.rs.getString("DESCRICAO_MESA"));
            
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldDescricaoMesa.setEnabled(true);
            
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        try {
          
            //conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.previous();
   
            jTextFieldCodMesa.setText(conecta.rs.getString("COD_MESA"));
            jTextFieldDescricaoMesa.setText(conecta.rs.getString("DESCRICAO_MESA"));
           
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldDescricaoMesa.setEnabled(true);
           

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        try{
            
            //conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.next();
            
           jTextFieldCodMesa.setText(conecta.rs.getString("COD_MESA"));
            jTextFieldDescricaoMesa.setText(conecta.rs.getString("DESCRICAO_MESA"));
            
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldDescricaoMesa.setEnabled(true);
           
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed
        
        
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
            
         try { 
            PreparedStatement pst = conecta.conn.prepareStatement("UPDATE MESA SET COD_MESA= ?, DESCRICAO_MESA=? WHERE COD_MESA='"+ jTextFieldCodMesa.getText()+"'"); //passagem do sql a ser executado
            pst.setInt(1, Integer.parseInt(jTextFieldCodMesa.getText()));
            pst.setString(2, jTextFieldDescricaoMesa.getText());// passagem dos parametros
            
           
            pst.executeUpdate(); //chamado do metodo para executar a instrucao
            JOptionPane.showMessageDialog(rootPane, "Registro Editado com Sucesso!");
            //preencherTabela("SELECT * FROM produto ORDER BY prodes limit 30");
            jButtonEditar.setEnabled(false);
            jTextFieldDescricaoMesa.setEnabled(false);
            
            jTextFieldCodMesa.setEnabled(true);
            jTextFieldCodMesa.setText("");
        jTextFieldDescricaoMesa.setText("");
       
                    // TODO add your handling code here:
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao editar \n Erro: " + ex);
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldCodMesaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodMesaKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
             String numero = jTextFieldCodMesa.getText();
            final String ZEROS = "0000";
            String s = String.valueOf(numero);
            String novoNumero = ZEROS.substring(s.length()) + s;   
            jTextFieldCodMesa.setText(novoNumero);
            
            conecta.executaSQL("SELECT * FROM MESA WHERE COD_MESA='"+jTextFieldCodMesa.getText()+"'");
            
            try {
                
                if(conecta.rs.next()){
                    jTextFieldDescricaoMesa.setText(conecta.rs.getString("DESCRICAO_MESA"));
                    
                    
        jTextFieldCodMesa.setEnabled(true);
        jTextFieldDescricaoMesa.setEnabled(true);
        
                    jButtonEditar.setEnabled(true);
                    jButtonExcluir.setEnabled(true);
                    
                    
                    
                } else {
                        JOptionPane.showMessageDialog(null, "Mesa não cadastrada!");
                         
        jTextFieldDescricaoMesa.setText("");
        
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(FrmMesa.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jTextFieldCodMesaKeyPressed

    private void jButtonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposActionPerformed
        jTextFieldDescricaoMesa.setText("");
        
        jTextFieldCodMesa.setText("");
        jTextFieldCodMesa.setEnabled(true);
        jTextFieldDescricaoMesa.setEnabled(true);
        
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
    }//GEN-LAST:event_jButtonLimparCamposActionPerformed
       public void preencherTabela(String SQL){
            
            ArrayList dados = new ArrayList();
            
            String[]  colunas = new String[]{"NUMERO","MESA"};
            
            conecta.executaSQL(SQL);
            try{ 
               conecta.rs.first();
                 do{
                     dados.add(new Object[]{conecta.rs.getInt("cod_mesa"),conecta.rs.getString("descricao_mesa")});
                 
                
            } while (conecta.rs.next());
                 
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList! \n Erro: " + ex);
                
            }
           ModeloTabela modelo = new ModeloTabela(dados, colunas);
           jTableEstado.setModel(modelo);
           jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(80);
           jTableEstado.getColumnModel().getColumn(0).setResizable(false);
           
           jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(180);
           jTableEstado.getColumnModel().getColumn(1).setResizable(false);
           
           jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(80);
           jTableEstado.getColumnModel().getColumn(2).setResizable(false);
           
           jTableEstado.getTableHeader().setReorderingAllowed(false);
           jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
           jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.LeveljTextFieldCodll, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMesa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMesa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimparCampos;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextFieldCodMesa;
    private javax.swing.JTextField jTextFieldDescricaoMesa;
    // End of variables declaration//GEN-END:variables
}
