/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import utilitarios.ConectaBanco;
import utilitarios.ModeloTabela;

/**
 *
 * @author gabrielbastos
 */
public class FrmProduto extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco(); // Instancia da classe de conexao
    
    public FrmProduto() {
        initComponents();
        conecta.conexao(); // chamada do metodo de conexao
        preencherTabela("SELECT * FROM produto ORDER BY prodes limit 30");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldCod = new javax.swing.JTextField();
        jTextFieldNomeProduto = new javax.swing.JTextField();
        jTextFieldPrecoCompra = new javax.swing.JTextField();
        jButtonNovo = new javax.swing.JButton();
        jButtonEditar = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonExcluir = new javax.swing.JButton();
        jButtonSair = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableEstado = new javax.swing.JTable();
        jButtonPrimeiro = new javax.swing.JButton();
        jButtonUltimo = new javax.swing.JButton();
        jButtonAnterior = new javax.swing.JButton();
        jButtonProximo = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldPrecoVenda = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextFieldQtde = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextFieldNomeProdutoReduzido = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldTipoEmbalagem = new javax.swing.JTextField();
        jButtonLimparCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Produtos");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setText("Código:");

        jLabel3.setText("Descrição");

        jLabel4.setText("Preço de compra");

        jTextFieldCod.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldCod.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodKeyPressed(evt);
            }
        });

        jTextFieldNomeProduto.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNomeProduto.setEnabled(false);

        jTextFieldPrecoCompra.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecoCompra.setEnabled(false);

        jButtonNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_199_CircledPlus_183316.png"))); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.setToolTipText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });

        jButtonEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_081_Pen_183209.png"))); // NOI18N
        jButtonEditar.setText("Aplicar Edições");
        jButtonEditar.setToolTipText("Editar");
        jButtonEditar.setEnabled(false);
        jButtonEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditarActionPerformed(evt);
            }
        });

        jButtonSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_178_Download_183297.png"))); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setToolTipText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_068_Cancel_183197.png"))); // NOI18N
        jButtonExcluir.setText("Excluir");
        jButtonExcluir.setToolTipText("Excluir");
        jButtonExcluir.setEnabled(false);
        jButtonExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExcluirActionPerformed(evt);
            }
        });

        jButtonSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_059_CircledOff_183188.png"))); // NOI18N
        jButtonSair.setToolTipText("Sair");
        jButtonSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSairActionPerformed(evt);
            }
        });

        jTableEstado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableEstado);

        jButtonPrimeiro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_previous-2_293643.png"))); // NOI18N
        jButtonPrimeiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrimeiroActionPerformed(evt);
            }
        });

        jButtonUltimo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_next_293690.png"))); // NOI18N
        jButtonUltimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUltimoActionPerformed(evt);
            }
        });

        jButtonAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAnteriorActionPerformed(evt);
            }
        });

        jButtonProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-right_293665.png"))); // NOI18N
        jButtonProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonProximoActionPerformed(evt);
            }
        });

        jLabel5.setText("Preço de venda");

        jTextFieldPrecoVenda.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldPrecoVenda.setEnabled(false);

        jLabel6.setText("Estoque atual");

        jTextFieldQtde.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldQtde.setEnabled(false);

        jLabel7.setText("Descrição Reduzida");

        jTextFieldNomeProdutoReduzido.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldNomeProdutoReduzido.setEnabled(false);

        jLabel8.setText("Tipo embalagem");

        jTextFieldTipoEmbalagem.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        jTextFieldTipoEmbalagem.setEnabled(false);

        jButtonLimparCampos.setText("Cancelar");
        jButtonLimparCampos.setToolTipText("Novo");
        jButtonLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimparCamposActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextFieldCod)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 441, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jTextFieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jTextFieldNomeProdutoReduzido, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel8)
                            .addGap(18, 18, 18)
                            .addComponent(jTextFieldTipoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNovo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonEditar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSalvar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonExcluir)
                        .addGap(10, 10, 10)
                        .addComponent(jButtonPrimeiro, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonUltimo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonAnterior, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonLimparCampos)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonProximo, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonSair, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldNomeProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel8)
                                .addComponent(jTextFieldTipoEmbalagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel7)
                                .addComponent(jTextFieldNomeProdutoReduzido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jTextFieldQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel5)
                                .addComponent(jTextFieldPrecoVenda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4)
                                .addComponent(jTextFieldPrecoCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jButtonLimparCampos)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonNovo)
                        .addComponent(jButtonEditar)
                        .addComponent(jButtonSalvar)
                        .addComponent(jButtonExcluir))
                    .addComponent(jButtonPrimeiro)
                    .addComponent(jButtonUltimo)
                    .addComponent(jButtonAnterior)
                    .addComponent(jButtonProximo)
                    .addComponent(jButtonSair))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("SFNS Display", 1, 18)); // NOI18N
        jLabel1.setText("Cadastro de Produtos");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_lollypop-lollipop.png"))); // NOI18N
        jLabel9.setText("G20PDV");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(318, 318, 318)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(119, 119, 119))
        );

        setSize(new java.awt.Dimension(892, 495));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        try {
            PreparedStatement pst = conecta.conn.prepareStatement("INSERT INTO produto (procod, prodes, prodesrdz, preco_compra_real, proprc1, quantidade, prounid, interno)values(?,?,?,?,?,?,?,'SIM')"); //passagem do sql a ser executado
            pst.setString(1, jTextFieldCod.getText());
            pst.setString(2, jTextFieldNomeProduto.getText());// passagem dos parametros
            pst.setString(3, jTextFieldNomeProdutoReduzido.getText());
            pst.setFloat(4, Float.parseFloat(jTextFieldPrecoCompra.getText()));
            
            pst.setString(5, jTextFieldPrecoVenda.getText());
            pst.setFloat(6, Float.parseFloat(jTextFieldQtde.getText()));
            pst.setString(7, jTextFieldTipoEmbalagem.getText());
            
            pst.executeUpdate(); //chamado do metodo para executar a instrucao
           
            JOptionPane.showMessageDialog(rootPane, "Registro Salvo!");
            //preencherTabela("SELECT * FROM produto ORDER BY procod");
                    // TODO add your handling code here:
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao salvar \n Erro: " + ex);
        }
        
        jTextFieldCod.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
        jTextFieldTipoEmbalagem.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldNomeProduto.setEnabled(false);
        jTextFieldPrecoCompra.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExcluirActionPerformed
                conecta.executaSQL("DELETE FROM produto WHERE procod='"+jTextFieldCod.getText()+"'");//chama metodo da classe ConectaBanco para exclusao
             JOptionPane.showMessageDialog(null, "Registro de PRODUTO excluído com sucesso!");
             
            jTextFieldCod.setText("");
            jTextFieldNomeProduto.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
        jTextFieldTipoEmbalagem.setText("");
        jTextFieldCod.setEnabled(true);
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldTipoEmbalagem.setEnabled(true);
        jTextFieldNomeProdutoReduzido.setEnabled(true);
        jTextFieldQtde.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExcluirActionPerformed

    private void jButtonSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSairActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonSairActionPerformed

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        // TODO add your handling code here:
        
        jTextFieldNomeProduto.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
        jTextFieldCod.setEnabled(true);
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldTipoEmbalagem.setEnabled(true);
        jTextFieldNomeProdutoReduzido.setEnabled(true);
        jTextFieldQtde.setEnabled(true);
        jButtonNovo.setEnabled(false);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonPrimeiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrimeiroActionPerformed
        // TODO add your handling code here:
        try{
            
            conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.first();
            jTextFieldCod.setText(conecta.rs.getString("procod"));
            jTextFieldNomeProduto.setText(conecta.rs.getString("prodes"));
            jTextFieldNomeProdutoReduzido.setText(conecta.rs.getString("prodesrdz"));
            jTextFieldPrecoCompra.setText(Float.toString(conecta.rs.getFloat("preco_compra_real")));
            jTextFieldTipoEmbalagem.setText(conecta.rs.getString("prounid"));
            jTextFieldPrecoVenda.setText(conecta.rs.getString("proprc1"));
            jTextFieldQtde.setText(conecta.rs.getString("quantidade"));
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldNomeProduto.setEnabled(true);
            jTextFieldPrecoCompra.setEnabled(true);
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonPrimeiroActionPerformed

    private void jButtonUltimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUltimoActionPerformed
        // TODO add your handling code here:
        try{
            
            conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.last();
            jTextFieldCod.setText(conecta.rs.getString("procod"));
            jTextFieldNomeProduto.setText(conecta.rs.getString("prodes"));
            jTextFieldNomeProdutoReduzido.setText(conecta.rs.getString("prodesrdz"));
            jTextFieldPrecoCompra.setText(Float.toString(conecta.rs.getFloat("preco_compra_real")));
            jTextFieldTipoEmbalagem.setText(conecta.rs.getString("prounid"));
            jTextFieldPrecoVenda.setText(conecta.rs.getString("proprc1"));
            jTextFieldQtde.setText(conecta.rs.getString("quantidade"));
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldNomeProduto.setEnabled(true);
            jTextFieldPrecoCompra.setEnabled(true);
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonUltimoActionPerformed

    private void jButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAnteriorActionPerformed
        // TODO add your handling code here:
        try {
          
            //conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.previous();
   
            jTextFieldCod.setText(conecta.rs.getString("procod"));
            jTextFieldNomeProduto.setText(conecta.rs.getString("prodes"));
            jTextFieldNomeProdutoReduzido.setText(conecta.rs.getString("prodesrdz"));
            jTextFieldPrecoCompra.setText(Float.toString(conecta.rs.getFloat("preco_compra_real")));
            jTextFieldTipoEmbalagem.setText(conecta.rs.getString("prounid"));
            jTextFieldPrecoVenda.setText(conecta.rs.getString("proprc1"));
            jTextFieldQtde.setText(conecta.rs.getString("quantidade"));
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldNomeProduto.setEnabled(true);
            jTextFieldPrecoCompra.setEnabled(true);

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonAnteriorActionPerformed

    private void jButtonProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonProximoActionPerformed
        // TODO add your handling code here:
        try{
            
            //conecta.executaSQL("SELECT * FROM produto");
            conecta.rs.next();
            
           jTextFieldCod.setText(conecta.rs.getString("procod"));
            jTextFieldNomeProduto.setText(conecta.rs.getString("prodes"));
            jTextFieldNomeProdutoReduzido.setText(conecta.rs.getString("prodesrdz"));
            jTextFieldPrecoCompra.setText(Float.toString(conecta.rs.getFloat("preco_compra_real")));
            jTextFieldTipoEmbalagem.setText(conecta.rs.getString("prounid"));
            jTextFieldPrecoVenda.setText(conecta.rs.getString("proprc1"));
            jTextFieldQtde.setText(conecta.rs.getString("quantidade"));
            
            jButtonEditar.setEnabled(true);
            jButtonExcluir.setEnabled(true);
            jTextFieldNomeProduto.setEnabled(true);
            jTextFieldPrecoCompra.setEnabled(true);
            
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar dados! \n Erro: " + ex);
        }
    }//GEN-LAST:event_jButtonProximoActionPerformed
        
        
    private void jButtonEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditarActionPerformed
            String interno="SIM";
         try { 
            PreparedStatement pst = conecta.conn.prepareStatement("UPDATE produto SET procod= ?, prodes=?, prodesrdz = ?, preco_compra_real = ?, proprc1 = ?, quantidade = ?, PROUNID=?, interno='SIM' WHERE procod= ?"); //passagem do sql a ser executado
            pst.setString(1, jTextFieldCod.getText());
            pst.setString(2, jTextFieldNomeProduto.getText());// passagem dos parametros
            pst.setString(3, jTextFieldNomeProdutoReduzido.getText());
            pst.setFloat(4, Float.parseFloat(jTextFieldPrecoCompra.getText()));
            pst.setString(5,jTextFieldPrecoVenda.getText());
            pst.setFloat(6, Float.parseFloat(jTextFieldQtde.getText()));
            pst.setString(7,jTextFieldTipoEmbalagem.getText());
            pst.setString(8, jTextFieldCod.getText());
           // pst.setString(8, interno);
            pst.executeUpdate(); //chamado do metodo para executar a instrucao
            JOptionPane.showMessageDialog(rootPane, "Registro Editado com Sucesso!");
            //preencherTabela("SELECT * FROM produto ORDER BY prodes limit 30");
            jButtonEditar.setEnabled(false);
            jTextFieldNomeProduto.setEnabled(false);
            jTextFieldPrecoVenda.setEnabled(false);
            jTextFieldCod.setEnabled(true);
            jTextFieldCod.setText("");
        jTextFieldNomeProduto.setText("");
        jTextFieldTipoEmbalagem.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
                    // TODO add your handling code here:
                    } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao editar \n Erro: " + ex);
        }
        
        
    }//GEN-LAST:event_jButtonEditarActionPerformed

    private void jTextFieldCodKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodKeyPressed
        
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            
             String numero = jTextFieldCod.getText();
            final String ZEROS = "00000000000000";
            String s = String.valueOf(numero);
            String novoNumero = ZEROS.substring(s.length()) + s;   
            jTextFieldCod.setText(novoNumero);
            
            conecta.executaSQL("SELECT * FROM PRODUTO WHERE PROCOD='"+jTextFieldCod.getText()+"'");
            
            try {
                
                if(conecta.rs.next()){
                    jTextFieldNomeProduto.setText(conecta.rs.getString("PRODES"));
                    jTextFieldNomeProdutoReduzido.setText(conecta.rs.getString("PRODESRDZ"));
                    jTextFieldTipoEmbalagem.setText(conecta.rs.getString("PROUNID"));
                    jTextFieldPrecoVenda.setText(conecta.rs.getString("PROPRC1"));
                    jTextFieldPrecoCompra.setText(Float.toString(conecta.rs.getFloat("PRECO_COMPRA_REAL")));      
                    jTextFieldQtde.setText(conecta.rs.getString("QUANTIDADE"));
                    
        jTextFieldCod.setEnabled(true);
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldTipoEmbalagem.setEnabled(true);
        jTextFieldNomeProdutoReduzido.setEnabled(true);
        jTextFieldQtde.setEnabled(true);
                    
                    jTextFieldPrecoVenda.setEnabled(true);
                    jButtonEditar.setEnabled(true);
                    jButtonExcluir.setEnabled(true);
                    
                    
                    
                } else {
                        JOptionPane.showMessageDialog(null, "Produto não cadastrado!");
                         
        jTextFieldNomeProduto.setText("");
        jTextFieldTipoEmbalagem.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
        jButtonEditar.setEnabled(false);
        jButtonNovo.setEnabled(true);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
                        }
            } catch (SQLException ex) {
                Logger.getLogger(FrmProduto.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
        }
        
        
        
        
        
    }//GEN-LAST:event_jTextFieldCodKeyPressed

    private void jButtonLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimparCamposActionPerformed
        jTextFieldNomeProduto.setText("");
        jTextFieldNomeProdutoReduzido.setText("");
        jTextFieldPrecoCompra.setText("");
        jTextFieldPrecoVenda.setText("");
        jTextFieldQtde.setText("");
        jTextFieldTipoEmbalagem.setText("");
        jTextFieldCod.setText("");
        jTextFieldCod.setEnabled(true);
        jTextFieldNomeProduto.setEnabled(true);
        jTextFieldPrecoCompra.setEnabled(true);
        jTextFieldPrecoVenda.setEnabled(true);
        jTextFieldTipoEmbalagem.setEnabled(true);
        jTextFieldNomeProdutoReduzido.setEnabled(true);
        jTextFieldQtde.setEnabled(true);
        jButtonNovo.setEnabled(true);
        jButtonEditar.setEnabled(false);
        jButtonExcluir.setEnabled(false);
        jButtonSalvar.setEnabled(false);
        jButtonAnterior.setEnabled(false);
        jButtonProximo.setEnabled(false);
        jButtonPrimeiro.setEnabled(false);
        jButtonUltimo.setEnabled(false);
        jButtonSair.setEnabled(true);
    }//GEN-LAST:event_jButtonLimparCamposActionPerformed
       public void preencherTabela(String SQL){
            
            ArrayList dados = new ArrayList();
            
            String[]  colunas = new String[]{"CÓDIGO","DESCRIÇÃO","PREÇO"};
            
            conecta.executaSQL(SQL);
            try{ 
               conecta.rs.first();
                 do{
                     dados.add(new Object[]{conecta.rs.getString("procod"),conecta.rs.getString("prodes"),conecta.rs.getFloat("proprc1")});
                 
                
            } while (conecta.rs.next());
                 
            } catch(SQLException ex){
                JOptionPane.showMessageDialog(rootPane, "Erro ao preencher o ArrayList! \n Erro: " + ex);
                
            }
           ModeloTabela modelo = new ModeloTabela(dados, colunas);
           jTableEstado.setModel(modelo);
           jTableEstado.getColumnModel().getColumn(0).setPreferredWidth(200);
           jTableEstado.getColumnModel().getColumn(0).setResizable(false);
           
           jTableEstado.getColumnModel().getColumn(1).setPreferredWidth(200);
           jTableEstado.getColumnModel().getColumn(1).setResizable(false);
           
           jTableEstado.getColumnModel().getColumn(2).setPreferredWidth(200);
           jTableEstado.getColumnModel().getColumn(2).setResizable(false);
           
           jTableEstado.getTableHeader().setReorderingAllowed(false);
           jTableEstado.setAutoResizeMode(jTableEstado.AUTO_RESIZE_OFF);
           jTableEstado.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        }
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
           // java.util.logging.Logger.getLogger(FrmEstado.class.getName()).log(java.util.logging.LeveljTextFieldCodll, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAnterior;
    private javax.swing.JButton jButtonEditar;
    private javax.swing.JButton jButtonExcluir;
    private javax.swing.JButton jButtonLimparCampos;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPrimeiro;
    private javax.swing.JButton jButtonProximo;
    private javax.swing.JButton jButtonSair;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUltimo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTableEstado;
    private javax.swing.JTextField jTextFieldCod;
    private javax.swing.JTextField jTextFieldNomeProduto;
    private javax.swing.JTextField jTextFieldNomeProdutoReduzido;
    private javax.swing.JTextField jTextFieldPrecoCompra;
    private javax.swing.JTextField jTextFieldPrecoVenda;
    private javax.swing.JTextField jTextFieldQtde;
    private javax.swing.JTextField jTextFieldTipoEmbalagem;
    // End of variables declaration//GEN-END:variables
}
