/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.DecimalFormat;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class Help extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    DefaultListModel MODELO;
    int enter = 0;
     DecimalFormat df = new DecimalFormat("0.00");
     String [] codig;
    public Help() {
       
        initComponents();
        this.setLocationRelativeTo(null);
         mostraPesquisa();
        jListMostraDados.setVisible(false);
        conecta.conexao(); 
        MODELO = new DefaultListModel();
        jListMostraDados.setModel(MODELO);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jTextFieldPesquisaNome = new javax.swing.JTextField();
        jListMostraDados = new javax.swing.JList<>();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabelProdes = new javax.swing.JLabel();
        jLabelCodProd = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabelPreco = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldPesquisaNome.setFont(new java.awt.Font("SFNS Display", 0, 11)); // NOI18N
        jTextFieldPesquisaNome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTextFieldPesquisaNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPesquisaNomeActionPerformed(evt);
            }
        });
        jTextFieldPesquisaNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaNomeKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextFieldPesquisaNomeKeyReleased(evt);
            }
        });
        jPanel1.add(jTextFieldPesquisaNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 80, 413, 23));

        jListMostraDados.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jListMostraDados.setPreferredSize(new java.awt.Dimension(2, 16));
        jListMostraDados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jListMostraDadosMousePressed(evt);
            }
        });
        jPanel1.add(jListMostraDados, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 410, 110));

        jLabel2.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel2.setText("Help! Busca inteligente por descrição");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 340, -1));

        jLabel3.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel3.setText("Preço:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 340, 120, -1));

        jLabel4.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel4.setText("Digite a descrição do produto");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 40, 340, -1));

        jLabelProdes.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jLabelProdes, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 520, 30));

        jLabelCodProd.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jLabelCodProd, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 410, 30));

        jLabel5.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel5.setText("Resultado:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 340, -1));

        jLabel6.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel6.setText("Código:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, 100, -1));

        jLabelPreco.setFont(new java.awt.Font("Tahoma", 1, 20)); // NOI18N
        jPanel1.add(jLabelPreco, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 340, 520, 30));

        jLabel7.setFont(new java.awt.Font("SFNS Display", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_chevron-left_293664.png"))); // NOI18N
        jLabel7.setText("Descrição:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 300, 120, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 787, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldPesquisaNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaNomeActionPerformed
       jListMostraDados.setVisible(false);
       enter=1;
    }//GEN-LAST:event_jTextFieldPesquisaNomeActionPerformed

    private void jTextFieldPesquisaNomeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaNomeKeyReleased
        if(enter==0)
            listaDePesquisa();
         else
        enter=0;
    
    }//GEN-LAST:event_jTextFieldPesquisaNomeKeyReleased

    private void jListMostraDadosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListMostraDadosMousePressed
        
        mostraPesquisa();
        jListMostraDados.setVisible(false);
    }//GEN-LAST:event_jListMostraDadosMousePressed

    private void jTextFieldPesquisaNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldPesquisaNomeKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ESCAPE){
            dispose();
            
         }
    }//GEN-LAST:event_jTextFieldPesquisaNomeKeyPressed

    public void listaDePesquisa(){
         try {
        conecta.executaSQL("SELECT PROCOD, PRODES, proprc1 FROM PRODUTO WHERE prodes like '"+ jTextFieldPesquisaNome.getText()+"%' ORDER BY prodes");
        MODELO.removeAllElements();
        int v = 0;
       codig= new String[6];
            while (conecta.rs.next() & v < 6){
                MODELO.addElement(conecta.rs.getString("prodes"));
                codig[v]=conecta.rs.getString("procod");
                v++;
            }
            if (v>=1){
                jListMostraDados.setVisible(true);
            }else{
                jListMostraDados.setVisible(false);
            }
            resultadoPesquisa();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(rootPane, "Erro ao mostrar lista: "+ ex);
        }
    }
    
    public void mostraPesquisa(){
        
        int linha = jListMostraDados.getSelectedIndex();
        if(linha>=0){
            conecta.executaSQL("SELECT PROCOD, PRODES, proprc1 FROM PRODUTO WHERE procod ='"+ codig[linha]+"'");
            
            resultadoPesquisa();
        }
    }
    public void resultadoPesquisa(){
        try {
            conecta.rs.first();
            jLabelCodProd.setText(conecta.rs.getString("procod"));
        jLabelProdes.setText(conecta.rs.getString("prodes"));
        String preco = (conecta.rs.getString("proprc1"));
        float f = Float.parseFloat(preco);
           
        jLabelPreco.setText("R$ "+(df.format(f)));
        } catch (SQLException ex) {
           //JOptionPane.showMessageDialog(rootPane,"Erro ao peencher os resultados"+ ex);
        }
        
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Help.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelCodProd;
    private javax.swing.JLabel jLabelPreco;
    private javax.swing.JLabel jLabelProdes;
    private javax.swing.JList<String> jListMostraDados;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldPesquisaNome;
    // End of variables declaration//GEN-END:variables
}
