/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Formularios;

import java.sql.SQLException;
import java.text.DateFormat;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import java.util.TimerTask;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.Timer;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import relatorios.Recibo;
import relatorios.RelatorioProdutividadeGarcom;
import relatorios.RelatorioVendaGeral;
import relatorios.RelatorioVendaPorCliente;
import relatorios.RelatorioVendaPorFinalizadora;
import relatorios.RelatorioVendaPorOperador;
import relatorios.RelatorioVendaPorProduto;
import utilitarios.ConectaBanco;

/**
 *
 * @author gabrielbastos
 */
public class Retaguarda extends javax.swing.JFrame {
      
      ConectaBanco conecta = new ConectaBanco();
      //tratando numeros decimais
      DecimalFormat df = new DecimalFormat("0.00");
       //Tratando hora
    SimpleDateFormat sdfhora = new SimpleDateFormat("HH:mm:ss");
    Date hora = Calendar.getInstance().getTime();
    String horaFormatada = sdfhora.format(hora);
    
    //Tratando data
    Date data = new Date();
    java.sql.Date dateSql = new java.sql.Date(data.getTime());
    String dataFormatada = java.text.DateFormat.getDateInstance(DateFormat.MEDIUM).format(data);
    SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy");
  //Variaveis pararmazenar datas para geração de relatórios
    String dataInicialRelatorios;
    String dataFinalRelatorios;
    String opcaoRelatorio;
   	public static final long TEMPO = (1000 * 10); // atualizar metodos a cada 10 segundos, aplicado na exibição da venda on-line
      
    
    public Retaguarda() {
  
        initComponents();
        this.setLocationRelativeTo(null);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        conecta.conexao();
        jPanelVendasOnline.setVisible(false);
        jDateChooserFinal.setVisible(false);
        jDateChooserInicial.setVisible(false);
        jLabelDataFinal.setVisible(false);
        jLabelDataInicial.setVisible(false);
        jLabelExibeVendas.setVisible(false);
        jLabelTitulo.setVisible(false);
        jLabelTitulo2.setVisible(false);
       
        
        //System.out.println(dataFormatada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jPanelVendasOnline = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jDateChooserFinal = new com.toedter.calendar.JDateChooser();
        jDateChooserInicial = new com.toedter.calendar.JDateChooser();
        jLabelDataInicial = new javax.swing.JLabel();
        jLabelDataFinal = new javax.swing.JLabel();
        jButtonAtualizarDadosVendas = new javax.swing.JButton();
        jLabelTitulo2 = new javax.swing.JLabel();
        jLabelExibeVendas = new javax.swing.JLabel();
        jButtonFecharPainel = new javax.swing.JButton();
        jCheckBoxVendaOnLine = new javax.swing.JCheckBox();
        jLabelTitulo3 = new javax.swing.JLabel();
        jLabelExibeLucro = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("PDVSysG20");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/if_lollypop-lollipop.png"))); // NOI18N
        jLabel1.setText("G20PDV");

        jPanelVendasOnline.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelTitulo.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelTitulo.setText("Painel de vendas on-line");

        jLabelDataInicial.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelDataInicial.setText("Data inicial");

        jLabelDataFinal.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelDataFinal.setText("Data final");

        jButtonAtualizarDadosVendas.setText("Atualizar");
        jButtonAtualizarDadosVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarDadosVendasActionPerformed(evt);
            }
        });

        jLabelTitulo2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelTitulo2.setText("Total de vendas : ");

        jLabelExibeVendas.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelExibeVendas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExibeVendas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButtonFecharPainel.setText("X");
        jButtonFecharPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharPainelActionPerformed(evt);
            }
        });

        jCheckBoxVendaOnLine.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jCheckBoxVendaOnLine.setText("Atualização em tempo real");
        jCheckBoxVendaOnLine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxVendaOnLineActionPerformed(evt);
            }
        });

        jLabelTitulo3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 14)); // NOI18N
        jLabelTitulo3.setText("Lucro:");

        jLabelExibeLucro.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabelExibeLucro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelExibeLucro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout jPanelVendasOnlineLayout = new javax.swing.GroupLayout(jPanelVendasOnline);
        jPanelVendasOnline.setLayout(jPanelVendasOnlineLayout);
        jPanelVendasOnlineLayout.setHorizontalGroup(
            jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                .addGap(125, 125, 125)
                .addComponent(jLabelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonFecharPainel))
            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasOnlineLayout.createSequentialGroup()
                        .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelDataInicial)
                            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                                .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButtonAtualizarDadosVendas)))
                        .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                                .addComponent(jLabelDataFinal)
                                .addGap(117, 117, 117))
                            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelVendasOnlineLayout.createSequentialGroup()
                        .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelExibeLucro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelExibeVendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))))
            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabelTitulo2))
                    .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jCheckBoxVendaOnLine)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabelTitulo3)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanelVendasOnlineLayout.setVerticalGroup(
            jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasOnlineLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelTitulo))
                    .addComponent(jButtonFecharPainel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelDataInicial)
                    .addComponent(jLabelDataFinal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelVendasOnlineLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jDateChooserInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jDateChooserFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonAtualizarDadosVendas))
                .addGap(30, 30, 30)
                .addComponent(jLabelTitulo2)
                .addGap(18, 18, 18)
                .addComponent(jLabelExibeVendas, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelTitulo3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelExibeLucro, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(jCheckBoxVendaOnLine)
                .addGap(32, 32, 32))
        );

        jMenu1.setText("Cadastros");

        jMenuItem8.setText("Produtos");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem8);

        jMenuItem16.setText("Mesas");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        jMenuItem14.setText("Funcionários");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem14);

        jMenuItem2.setText("Estados");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setText("Cidades");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuItem6.setText("Clientes");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem6);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Compra");

        jMenuItem1.setText("Entrada de mercadorias");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem1);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Venda");

        jMenuItem13.setText("Venda on-line");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Relatórios");

        jMenuItem15.setText("Produtos Internos");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuItem11.setText("Venda por Produto");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem11);

        jMenuItem9.setText("Venda por Cliente");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem9);

        jMenuItem10.setText("Flash de Caixa");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem10);

        jMenuItem19.setText("Produtividade do Garçom");
        jMenuItem19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem19ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem19);

        jMenuItem20.setText("Mesas Abertas");
        jMenuItem20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem20ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem20);

        jMenuItem5.setText("Venda por finalizadora");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem5);

        jMenuItem12.setText("Venda Geral");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem12);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Gerenciamento");

        jMenuItem17.setText("Ajuste manual de estoque");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem17);

        jMenuItem18.setText("Configuração BD");
        jMenuItem18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem18ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem18);

        jMenuItem7.setText("Consulta estoque de produto");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu6.add(jMenuItem7);

        jMenuBar1.add(jMenu6);

        jMenu5.setText("Sair");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(861, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanelVendasOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanelVendasOnline, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 160, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
        );

        setSize(new java.awt.Dimension(1360, 726));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
         FrmEstado frmEstado = new FrmEstado();
         frmEstado.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
            new FrmCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
         FrmCidade frmCidade = new FrmCidade();
         frmCidade.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        FrmProduto frmproduto = new FrmProduto();
        frmproduto.setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jButtonAtualizarDadosVendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarDadosVendasActionPerformed
        jCheckBoxVendaOnLine.setSelected(false);
        Date dataInicial = jDateChooserInicial.getDate();
        Date dataFinal = jDateChooserFinal.getDate();
        
       
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
        
        
        conecta.executaSQL("SELECT SUM (TRNVLR) AS TOTAL FROM TRANSACAO WHERE TRNTIP='1' AND TRNDAT BETWEEN'"+ dataInicial+"' AND '"+ dataFinal+"'");
        
          try {
              while(conecta.rs.next()){
                  
                  
                  Float d = conecta.rs.getFloat("TOTAL");
        
                  jLabelExibeVendas.setText("R$  "+(df.format(d)));
                  
                  //jLabelExibeVendas.setText(Double.toString(df.format(d)));
                  
                  
              } } catch (SQLException ex) {
              Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
          }
         conecta.executaSQL("SELECT\n" +
"        SUM(\n" +
"            (B.ITVVLRTOT)-(A.PRECO_COMPRA_REAL*B.QUANTIDADE) )AS LUCROVALOR\n" +
"        FROM PRODUTO A \n" +
"            INNER JOIN ITEVDA B\n" +
"                ON A.PROCOD=B.PROCOD\n" +
"                INNER JOIN TRANSACAO C ON B.TRNSEQ=C.TRNSEQ\n" +
"               \n" +
"            WHERE B.TRNDAT BETWEEN'"+ dataInicial+"' AND '"+ dataFinal+"'\n" +
"            AND C.TRNTIP='1'");
        
          try {
              while(conecta.rs.next()){
                  
                  Float d13 = conecta.rs.getFloat("LUCROVALOR");
                  float perc = (d13*10)/100;
                  System.out.println(perc);
                  d13 = d13 + perc;
                  System.out.println(d13);
                  jLabelExibeLucro.setText("R$  "+df.format(d13));
                  
                  
              } } catch (SQLException ex) {
              Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
          }
        
        
    }//GEN-LAST:event_jButtonAtualizarDadosVendasActionPerformed

    
    void atualizaVendaAutomatico() {
        
        //DecimalFormat df = new DecimalFormat("0.00");
       
        conecta.executaSQL("SELECT SUM (TRNVLR) AS TOTAL FROM TRANSACAO WHERE TRNTIP='1' AND TRNDAT BETWEEN'"+ dateSql+"' AND '"+ dateSql+"'");
        
          try {
              while(conecta.rs.next()){
                  
                  Float d = conecta.rs.getFloat("TOTAL");
                  
                  jLabelExibeVendas.setText("R$  "+df.format(d));
                  
                  
              } } catch (SQLException ex) {
              Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
          }
        
       //PEGANDO O LUCRO
        conecta.executaSQL("SELECT\n" +
"        SUM(\n" +
"            (B.ITVVLRTOT)-(A.PRECO_COMPRA_REAL*B.QUANTIDADE) )AS LUCROVALOR\n" +
"        FROM PRODUTO A \n" +
"            INNER JOIN ITEVDA B\n" +
"                ON A.PROCOD=B.PROCOD\n" +
"                INNER JOIN TRANSACAO C ON B.TRNSEQ=C.TRNSEQ\n" +
"               \n" +
"            WHERE B.TRNDAT BETWEEN'"+ dateSql+"' AND '"+ dateSql+"'\n" +
"            AND C.TRNTIP='1'");
        
          try {
              while(conecta.rs.next()){
                  
                  Float d1 = conecta.rs.getFloat("LUCROVALOR");
                   float perc = (d1*10)/100;
                  System.out.println(perc);
                  d1 = d1 + perc;
                  jLabelExibeLucro.setText("R$  "+df.format(d1));
                  
                  
              } } catch (SQLException ex) {
              Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
          } 
        
    }
    
    
    
    
    
    
    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        jPanelVendasOnline.setVisible(true);
        jDateChooserFinal.setVisible(true);
        jDateChooserInicial.setVisible(true);
        jLabelDataFinal.setVisible(true);
        jLabelDataInicial.setVisible(true);
        jLabelExibeVendas.setVisible(true);
        jLabelTitulo.setVisible(true);
        jLabelTitulo2.setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jButtonFecharPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharPainelActionPerformed
        jPanelVendasOnline.setVisible(false);
        jDateChooserFinal.setVisible(false);
        jDateChooserInicial.setVisible(false);
        jLabelDataFinal.setVisible(false);
        jLabelDataInicial.setVisible(false);
        jLabelExibeVendas.setVisible(false);
        jLabelTitulo.setVisible(false);
        jLabelTitulo2.setVisible(false);
    }//GEN-LAST:event_jButtonFecharPainelActionPerformed

    private void jCheckBoxVendaOnLineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxVendaOnLineActionPerformed
           
                
                atualizaVendaAutomatico(); 
        
		Timer timer = null;
		if (timer == null) {
			timer = new Timer();
			TimerTask tarefa = new TimerTask() {
				public void run() {
					try {
                                            if(jCheckBoxVendaOnLine.isSelected()){
						atualizaVendaAutomatico();
                                            }
					} catch (Exception e) {
						e.printStackTrace();
					}
				}
			};
			timer.scheduleAtFixedRate(tarefa, TEMPO, TEMPO);
		}	
	
                

          
    }//GEN-LAST:event_jCheckBoxVendaOnLineActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
            new RelatorioVendaPorProduto().setVisible(true);

    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        new FrmFuncionario().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
                new RelatorioVendaPorCliente().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
            new RelatorioVendaPorFinalizadora().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
                    new RelatorioVendaPorOperador().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        new RelatorioVendaGeral().setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem18ActionPerformed
                    JOptionPane.showMessageDialog(rootPane, "Acesso restrito ao desenvolvedor!");
    }//GEN-LAST:event_jMenuItem18ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
         new EntradaMercadoria().setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        new AjusteManualEstoque().setVisible(true);
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        new ConsultaEstoqueProduto().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
             try {
              
                   conecta.executaSQL("SELECT\n" +
"PROCOD,\n" +
"PRODES,\n" +
"QUANTIDADE,\n" +
"(\n" +
"SELECT COUNT(*) FROM PRODUTO) AS TOTAL,\n" +
"(\n" +
"SELECT CAST(SUM(QUANTIDADE)AS bigint) FROM PRODUTO) AS QTDE_ITENS\n" +
"FROM PRODUTO\n" +
"WHERE INTERNO='SIM'\n" +
"ORDER BY PRODES ASC");
  
             
                 
                  
        HashMap filtro = new HashMap<>();
                  
               
                  
                  JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                  JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/Relatorio_Produtos_Internos.jasper",filtro, relatResul);
                  JasperViewer jv = new JasperViewer(jpPrint, false);
                  jv.setVisible(true);
                  
              
                  
             
               
          } catch (JRException ex) {
              System.out.println("Erro Relatorio: "+ex);  
          
                Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro no sql: "+ex);
                
            }
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
                    new FrmMesa().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void jMenuItem19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem19ActionPerformed
        new RelatorioProdutividadeGarcom().setVisible(true);
    }//GEN-LAST:event_jMenuItem19ActionPerformed

    private void jMenuItem20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem20ActionPerformed
        try {
              
                   conecta.executaSQL("SELECT\n" +
"MESA,\n" +
"NOMEFUNC_PRE,\n" +
"PRODES_PRE,\n" +
"SUM(QUANTIDADE_PRE) AS QUANTIDADE_PRE\n" +
"FROM CONSUMO\n" +
"GROUP BY PRODES_PRE, MESA, NOMEFUNC_PRE\n" +
"ORDER BY MESA ASC");
  
             
                 
                  
        HashMap filtro = new HashMap<>();
                  
               
                  
                  JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                  JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/RelatorioMesasAbertas.jasper",filtro, relatResul);
                  JasperViewer jv = new JasperViewer(jpPrint, false);
                  jv.setVisible(true);
                  
              
                  
             
               
          } catch (JRException ex) {
              System.out.println("Erro Relatorio: "+ex);  
          
                Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro no sql: "+ex);
                
            }
    }//GEN-LAST:event_jMenuItem20ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Retaguarda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Retaguarda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Retaguarda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Retaguarda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Retaguarda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarDadosVendas;
    private javax.swing.JButton jButtonFecharPainel;
    private javax.swing.JCheckBox jCheckBoxVendaOnLine;
    private com.toedter.calendar.JDateChooser jDateChooserFinal;
    private com.toedter.calendar.JDateChooser jDateChooserInicial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelDataFinal;
    private javax.swing.JLabel jLabelDataInicial;
    private javax.swing.JLabel jLabelExibeLucro;
    private javax.swing.JLabel jLabelExibeVendas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JLabel jLabelTitulo2;
    private javax.swing.JLabel jLabelTitulo3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanelVendasOnline;
    // End of variables declaration//GEN-END:variables
}
