/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import Formularios.Retaguarda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class Recibo extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendaPorCliente
     */
    ConectaBanco conecta = new ConectaBanco();
    public Recibo() {
        initComponents();
        this.setLocationRelativeTo(null);
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSelecaoIntervalo = new javax.swing.JLabel();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jTextFieldPlaca = new javax.swing.JTextField();
        jLabelSelecaoIntervalo1 = new javax.swing.JLabel();
        jLabelSelecaoIntervalo2 = new javax.swing.JLabel();
        jTextFieldCupom = new javax.swing.JTextField();
        jLabelSelecaoIntervalo3 = new javax.swing.JLabel();
        jButtonGerarRelatorios = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSelecaoIntervalo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo.setText("Insira a placa do veículo, selecione o intervalo e clique em \"Gerar\".");

        jLabelSelecaoIntervalo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo1.setText("Placa:");

        jLabelSelecaoIntervalo2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo2.setText("Cupom:");

        jLabelSelecaoIntervalo3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo3.setText("Data:");

        jButtonGerarRelatorios.setText("Gerar");
        jButtonGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatoriosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelSelecaoIntervalo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSelecaoIntervalo3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSelecaoIntervalo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(31, 31, 31)
                                .addComponent(jLabelSelecaoIntervalo2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCupom, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGerarRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSelecaoIntervalo)
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldPlaca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSelecaoIntervalo1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCupom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelSelecaoIntervalo2)))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelSelecaoIntervalo3)
                            .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jButtonGerarRelatorios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatoriosActionPerformed
        
        Date relDataIni = jDateChooserDataInicial.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String placa = jTextFieldPlaca.getText();
        String cupom = jTextFieldCupom.getText();
        
          conecta.executaSQL("SELECT\n" +
                    "A.TRNSEQ,\n" +
                    "A.FUNCOD,\n" +
                    "A.TRNVLR,\n" +
                    "A.TRNDAT,\n" +
                    "A.PLACA,\n" +
                    "A.NOME_CLIENTE,\n" +
                    "B.PROCOD,\n" +
                    "B.QUANTIDADE,\n" +
                    "B.ITVVLRTOT,\n" +
                    "C.PRODES,\n" +
                    "D.COD_FINALIZADORA,\n" +
                    "E.DESCRICAO_FINALIZADORA,\n" +
                    "F.NOME_FUNCIONARIO\n" +
                    "\n" +
                    "FROM TRANSACAO A\n" +
                    "INNER JOIN\n" +
                    "ITEVDA B ON\n" +
                    "A.TRNSEQ =  B.TRNSEQ\n" +
                    "INNER JOIN  PRODUTO C\n" +
                    "ON\n" +
                    "C.PROCOD=B.PROCOD\n" +
                    "INNER JOIN FINALIZACAO D\n" +
                    "ON\n" +
                    "A.TRNSEQ=D.TRNSEQ\n" +
                    "INNER JOIN FINALIZADORA E\n" +
                    "ON\n" +
                    "D.COD_FINALIZADORA=CAST(E.COD_FINALIZADORA AS TEXT)\n" +
                    "INNER JOIN FUNCIONARIO F\n" +
                    "ON\n" +
                    "A.FUNCOD=CAST(F.FUNCOD AS TEXT)\n" +
                    "WHERE\n" +
                    "A.TRNTIP='1'\n" +
                    "AND\n" +
                    "A.TRNDAT = '"+ relDataIni +"'\n" +
                    "AND\n" +
                    "A.TRNSEQ='"+cupom+"' AND A.PLACA='"+placa+"'");
          
          
           
            
         
          try {
               if (conecta.rs.next()){
              while(conecta.rs.next()){
                  
                  HashMap filtro = new HashMap<>();
                  
               filtro.put("placa", placa);                 
               filtro.put("trnseq", cupom); 
               filtro.put("data", sdf.format(relDataIni));
              
                 
                  
                  JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                  JasperPrint jpPrint = JasperFillManager.fillReport("relatorios/Recibo.jasper",filtro, relatResul);
                  JasperViewer jv = new JasperViewer(jpPrint, false);
                  jv.setVisible(true);
                  
              }  
                  
              } else {
                   JOptionPane.showMessageDialog(null, "Sem informações suficientes para gerar o recibo!");
               } 
          } catch (JRException ex) {
              System.out.println("Erro Relatorio: "+ex);  
          } catch (SQLException ex) {
                Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro no sql: "+ex);
                
            }
          
     
    }//GEN-LAST:event_jButtonGerarRelatoriosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recibo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recibo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRelatorios;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private javax.swing.JLabel jLabelSelecaoIntervalo;
    private javax.swing.JLabel jLabelSelecaoIntervalo1;
    private javax.swing.JLabel jLabelSelecaoIntervalo2;
    private javax.swing.JLabel jLabelSelecaoIntervalo3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCupom;
    private javax.swing.JTextField jTextFieldPlaca;
    // End of variables declaration//GEN-END:variables
}
