/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import Formularios.Retaguarda;
import java.awt.event.KeyEvent;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class RelatorioVendaPorFinalizadora extends javax.swing.JFrame {

    ConectaBanco conecta = new ConectaBanco();
    public RelatorioVendaPorFinalizadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSelecaoIntervalo = new javax.swing.JLabel();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jButtonGerarRelatorios = new javax.swing.JButton();
        jDateChooserDataFinal = new com.toedter.calendar.JDateChooser();
        jTextFieldCodFinalizadora = new javax.swing.JTextField();
        jLabelSelecaoIntervalo1 = new javax.swing.JLabel();
        jLabelExibeFinalizadora = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSelecaoIntervalo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo.setText("Insira o código da finalizadora, selecione o intervalo e clique em \"Gerar\".");

        jButtonGerarRelatorios.setText("Gerar");
        jButtonGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatoriosActionPerformed(evt);
            }
        });

        jTextFieldCodFinalizadora.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodFinalizadoraKeyPressed(evt);
            }
        });

        jLabelSelecaoIntervalo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo1.setText("Código da finalizadora");

        jLabelExibeFinalizadora.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelExibeFinalizadora.setText("GERAL");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonGerarRelatorios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelSelecaoIntervalo1)
                        .addGap(10, 10, 10)
                        .addComponent(jTextFieldCodFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelExibeFinalizadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabelSelecaoIntervalo))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabelSelecaoIntervalo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabelSelecaoIntervalo1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextFieldCodFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelExibeFinalizadora, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonGerarRelatorios)
                        .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatoriosActionPerformed
         
          Date relDataIni = jDateChooserDataInicial.getDate();
        Date relDataFin = jDateChooserDataFinal.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String stringCodFinalizadora = jTextFieldCodFinalizadora.getText();
        
        if("".equals(jTextFieldCodFinalizadora.getText())){
              
            
            
            

        try {
           
              
               conecta.executaSQL("SELECT\n" +
                "A.TRNDAT,\n" +
                "A.COD_FINALIZADORA,\n" +
                "B.DESCRICAO_FINALIZADORA,\n" +
                "to_char(CAST(SUM (A.VALOR_PAGO)AS DECIMAL(18,2)), 'L9G999G990D99') AS TOTAL\n" +
                "FROM\n" +
                "FINALIZACAO A INNER JOIN  FINALIZADORA B\n" +
                "ON\n" +
                "A.COD_FINALIZADORA=CAST(B.COD_FINALIZADORA AS TEXT)\n" +
                "WHERE\n" +
                "A.TRNDAT BETWEEN '"+sdf.format(relDataIni)+ "' AND '"+sdf.format(relDataFin)+"'\n" +
                "\n" +
                "\n" +
                "GROUP BY A.TRNDAT,A.COD_FINALIZADORA,B.DESCRICAO_FINALIZADORA\n" +
                "ORDER BY A.TRNDAT DESC");
            
   
                        HashMap filtro = new HashMap<>();
                        
                        System.out.println(stringCodFinalizadora);
                   
                    filtro.put("dataIni", sdf.format(relDataIni));
                    filtro.put("dataFin", sdf.format(relDataFin));
                    

                    JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                    JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/VendaProFinalizadoraGeral.jasper",filtro, relatResul);
                    JasperViewer jv = new JasperViewer(jpPrint, false);
                    jv.setVisible(true);
                    
                    

          
        } catch (JRException ex) {
            System.out.println("Erro Relatorio: "+ex);
        
            Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Erro no sql: "+ex);
            
        }
        
      
        }else{
        
        

        conecta.executaSQL("SELECT\n" +
                "A.TRNDAT,\n" +
                "A.COD_FINALIZADORA,\n" +
                "B.DESCRICAO_FINALIZADORA,\n" +
                "to_char(CAST(SUM (A.VALOR_PAGO)AS DECIMAL(18,2)), 'L9G999G990D99') AS TOTAL\n" +
                "FROM\n" +
                "FINALIZACAO A INNER JOIN  FINALIZADORA B\n" +
                "ON\n" +
                "A.COD_FINALIZADORA=CAST(B.COD_FINALIZADORA AS TEXT)\n" +
                "WHERE\n" +
                "A.TRNDAT BETWEEN '"+sdf.format(relDataIni)+ "' AND '"+sdf.format(relDataFin)+"'\n" +
                "AND\n" +
                "A.COD_FINALIZADORA ='"+stringCodFinalizadora+"'\n" +
                "\n" +
                "\n" +
                "GROUP BY A.TRNDAT,A.COD_FINALIZADORA,B.DESCRICAO_FINALIZADORA\n" +
                "ORDER BY A.TRNDAT DESC");

        try {
            
              
                
                  
                   
                        
                    
                    
                        HashMap filtro = new HashMap<>();
                           System.out.println(stringCodFinalizadora);

                    filtro.put("cod_finalizadora", jTextFieldCodFinalizadora.getText());
                    filtro.put("dataIni", sdf.format(relDataIni));
                    filtro.put("dataFin", sdf.format(relDataFin));
                    

                    JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                    JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/RelatorioVendaPorFinalizadoraEspecifica.jasper",filtro, relatResul);
                    JasperViewer jv = new JasperViewer(jpPrint, false);
                    jv.setVisible(true);
                        
                            
                            
                                               
 
                

           
        } catch (JRException ex) {
            System.out.println("Erro Relatorio: "+ex);
        
            Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Erro no sql: "+ex);

        }
        
        }
    }//GEN-LAST:event_jButtonGerarRelatoriosActionPerformed

    private void jTextFieldCodFinalizadoraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodFinalizadoraKeyPressed
      
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
           conecta.executaSQL("SELECT * FROM finalizadora WHERE cod_finalizadora='"+ jTextFieldCodFinalizadora.getText()+"'");
           
           
             try {
                 if(conecta.rs.next()){
                     jLabelExibeFinalizadora.setText(conecta.rs.getString("descricao_finalizadora"));
                 }else{
                     JOptionPane.showMessageDialog(rootPane, "Finalizadora não cadastrada!");
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(Level.SEVERE, null, ex);
             }
                    
                }
        
        
    }//GEN-LAST:event_jTextFieldCodFinalizadoraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVendaPorFinalizadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRelatorios;
    private com.toedter.calendar.JDateChooser jDateChooserDataFinal;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private javax.swing.JLabel jLabelExibeFinalizadora;
    private javax.swing.JLabel jLabelSelecaoIntervalo;
    private javax.swing.JLabel jLabelSelecaoIntervalo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodFinalizadora;
    // End of variables declaration//GEN-END:variables
}
