/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import Formularios.Retaguarda;
import java.awt.event.KeyEvent;
import java.net.URL;
import java.sql.Connection;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class RelatorioVendaPorOperador extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendaPorCliente
     */
    ConectaBanco conecta = new ConectaBanco();
    public RelatorioVendaPorOperador() {
        initComponents();
        this.setLocationRelativeTo(null);
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSelecaoIntervalo = new javax.swing.JLabel();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jButtonGerarRelatorios = new javax.swing.JButton();
        jDateChooserDataFinal = new com.toedter.calendar.JDateChooser();
        jTextFieldCodOperador = new javax.swing.JTextField();
        jLabelSelecaoIntervalo1 = new javax.swing.JLabel();
        jLabelNomeOperador = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSelecaoIntervalo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo.setText("Insira o código do operador, selecione o intervalo e clique em \"Gerar\".");

        jDateChooserDataInicial.setMinimumSize(new java.awt.Dimension(40, 20));

        jButtonGerarRelatorios.setText("Gerar");
        jButtonGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatoriosActionPerformed(evt);
            }
        });

        jDateChooserDataFinal.setMinimumSize(new java.awt.Dimension(40, 20));

        jTextFieldCodOperador.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextFieldCodOperadorKeyPressed(evt);
            }
        });

        jLabelSelecaoIntervalo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo1.setText("Código do operador:");

        jLabelNomeOperador.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(jLabelSelecaoIntervalo))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelSelecaoIntervalo1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCodOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonGerarRelatorios)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelNomeOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSelecaoIntervalo)
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelNomeOperador, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelSelecaoIntervalo1)
                        .addComponent(jTextFieldCodOperador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonGerarRelatorios)
                    .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatoriosActionPerformed
        
        Date relDataIni = jDateChooserDataInicial.getDate();
        Date relDataFin = jDateChooserDataFinal.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String codOperador = jTextFieldCodOperador.getText();
        
          
           
            
         
          try {
              
              conecta.executaSQL("SELECT\n" +
"(\n" +
"SELECT TO_CHAR(CAST(SUM (TRNVLR)AS DECIMAL(18,2)), 'L9G999G990D99') FROM TRANSACAO WHERE FUNCOD='"+codOperador+"' AND TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"'  )AS VENDA_BRUTA,\n" +
"(\n" +
"SELECT  TO_CHAR(CAST(SUM (TRNVLR)AS DECIMAL(18,2)), 'L9G999G990D99') FROM TRANSACAO WHERE TRNTIP='7' AND FUNCOD='"+codOperador+"' AND TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"')AS CANCELAMENTOS,\n" +
"(SELECT  (SELECT CAST(SUM (TRNVLR)AS DECIMAL(18,2)) FROM TRANSACAO WHERE FUNCOD='"+codOperador+"' AND TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"') - (SELECT CAST(SUM (TRNVLR)AS DECIMAL(18,2)) FROM TRANSACAO WHERE TRNTIP='7' AND FUNCOD='"+codOperador+"' AND TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"' )) AS  VENDA_LIQUIDA,\n" +
"(SELECT TO_CHAR(CAST(SUM (ITVVLRTOT)AS DECIMAL(18,2)), 'L9G999G990D99') FROM ITEVDA WHERE TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"' AND TRNSEQ=A.TRNSEQ) AS VALOR_CONSUMO,\n" +
"\n" +
"\n" +
"A.TRNSEQ,\n" +
"A.FUNCOD,\n" +
"A.TRNVLR,\n" +
"A.TRNDAT,\n" +
"A.MESA,\n" +
"A.FUNCOD_PRE,\n" +
"B.PROCOD,\n" +
"B.QUANTIDADE,\n" +
"TO_CHAR(CAST(B.ITVVLRTOT AS DECIMAL(18,2)),'L9G999G990D99') AS ITVVLRTOT,\n" +
"C.PRODES,\n" +
"F.NOME_FUNCIONARIO,\n" +
"(SELECT TO_CHAR(CAST(SUM (TROCO)AS DECIMAL(18,2)), 'L9G999G990D99') FROM FINALIZACAO WHERE TRNSEQ= A.TRNSEQ) AS TROCO,\n" +
"(SELECT TO_CHAR(CAST(SUM (TRNVLR)AS DECIMAL(18,2)), 'L9G999G990D99') FROM TRANSACAO WHERE TRNSEQ= A.TRNSEQ) AS VALOR_CUPOM,\n" +
"(SELECT TO_CHAR(CAST(SUM (VALOR_PAGO)AS DECIMAL(18,2)), 'L9G999G990D99') FROM FINALIZACAO WHERE TRNSEQ= A.TRNSEQ) AS VALOR_PAGO\n" +
"\n" +
"\n" +
"FROM TRANSACAO A\n" +
"INNER JOIN\n" +
"ITEVDA B ON\n" +
"A.TRNSEQ =  B.TRNSEQ\n" +
"INNER JOIN  PRODUTO C\n" +
"ON\n" +
"C.PROCOD=B.PROCOD\n" +
"\n" +
"INNER JOIN FUNCIONARIO F\n" +
"ON\n" +
"A.FUNCOD=CAST(F.FUNCOD AS TEXT)\n" +
"\n" +
"WHERE\n" +
"\n" +
"A.TRNDAT BETWEEN '"+sdf.format(relDataIni)+"' AND '"+sdf.format(relDataFin)+"'\n" +
"AND\n" +
"A.FUNCOD= '"+codOperador+"'\n" +
"\n" +
"GROUP BY A.TRNSEQ, B.PROCOD, B.QUANTIDADE, B.ITVVLRTOT, C.PRODES, F.NOME_FUNCIONARIO\n" +
"ORDER BY A.TRNSEQ DESC");
              
            
                   HashMap filtro = new HashMap<>();
                
               filtro.put("funcod", codOperador);
               filtro.put("dataIni", sdf.format(relDataIni));
               filtro.put("dataFin", sdf.format(relDataFin));
               filtro.put("$P{SUBREPORT_DIR}", true); 
               filtro.put("$P{REPORT_CONNECTION}", conecta ) ;      
                 
                  
                  JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                  JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/RelatorioVendaPorOperador.jasper",filtro, relatResul);
                  JasperViewer jv = new JasperViewer(jpPrint, false);
                  jv.setVisible(true);
                  
              
                  
              
          } catch (JRException ex) {
              System.out.println("Erro Relatorio: "+ex);  
          
                Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro no sql: "+ex);
                
            }
          
     
    }//GEN-LAST:event_jButtonGerarRelatoriosActionPerformed

    private void jTextFieldCodOperadorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextFieldCodOperadorKeyPressed
                         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
           
           conecta.executaSQL("SELECT * FROM funcionario WHERE funcod='"+ jTextFieldCodOperador.getText()+"'");
           
           
             try {
                 if(conecta.rs.next()){
                     jLabelNomeOperador.setText(conecta.rs.getString("nome_funcionario"));
                 }else{
                     JOptionPane.showMessageDialog(rootPane, "Operador não cadastrado!");
                     jTextFieldCodOperador.setText("");
                     jLabelNomeOperador.setText("");
                 }
             } catch (SQLException ex) {
                 Logger.getLogger(RelatorioVendaPorFinalizadora.class.getName()).log(Level.SEVERE, null, ex);
             }
                    
                }
    }//GEN-LAST:event_jTextFieldCodOperadorKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVendaPorOperador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonGerarRelatorios;
    private com.toedter.calendar.JDateChooser jDateChooserDataFinal;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private javax.swing.JLabel jLabelNomeOperador;
    private javax.swing.JLabel jLabelSelecaoIntervalo;
    private javax.swing.JLabel jLabelSelecaoIntervalo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCodOperador;
    // End of variables declaration//GEN-END:variables
}
