/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package relatorios;

import Formularios.HelpCliente;
import Formularios.Retaguarda;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import utilitarios.ConectaBanco;

/**
 *
 * @author Gabriel Bastos
 */
public class RelatorioVendaPorCliente extends javax.swing.JFrame {

    /**
     * Creates new form RelatorioVendaPorCliente
     */
    ConectaBanco conecta = new ConectaBanco();
    public RelatorioVendaPorCliente() {
        initComponents();
        this.setLocationRelativeTo(null);
        conecta.conexao();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelSelecaoIntervalo = new javax.swing.JLabel();
        jDateChooserDataInicial = new com.toedter.calendar.JDateChooser();
        jButtonGerarRelatorios = new javax.swing.JButton();
        jDateChooserDataFinal = new com.toedter.calendar.JDateChooser();
        jTextFieldCod_Cliente = new javax.swing.JTextField();
        jLabelSelecaoIntervalo1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabelSelecaoIntervalo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo.setText("Insira o código do cliente, selecione o intervalo e clique em \"Gerar\".");

        jButtonGerarRelatorios.setText("Gerar");
        jButtonGerarRelatorios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGerarRelatoriosActionPerformed(evt);
            }
        });

        jLabelSelecaoIntervalo1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelSelecaoIntervalo1.setText("Código do cliente");

        jButton1.setBackground(new java.awt.Color(153, 255, 153));
        jButton1.setForeground(new java.awt.Color(255, 0, 0));
        jButton1.setText("AJUDA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonGerarRelatorios)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(127, 127, 127)
                            .addComponent(jLabelSelecaoIntervalo1)
                            .addGap(10, 10, 10)
                            .addComponent(jTextFieldCod_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(80, 80, 80)
                            .addComponent(jLabelSelecaoIntervalo))))
                .addContainerGap(47, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabelSelecaoIntervalo)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(jLabelSelecaoIntervalo1))
                            .addComponent(jTextFieldCod_Cliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserDataFinal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButtonGerarRelatorios)
                        .addComponent(jDateChooserDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonGerarRelatoriosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGerarRelatoriosActionPerformed
        
        Date relDataIni = jDateChooserDataInicial.getDate();
        Date relDataFin = jDateChooserDataFinal.getDate();
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
        String cod_cliente = jTextFieldCod_Cliente.getText();
        
            
         
          try {
              
              conecta.executaSQL(
"SELECT\n" +
"A.TRNSEQ,\n" +
"A.FUNCOD,\n" +
"CAST(SUM (A.TRNVLR)AS DECIMAL(18,2)) as TRNVLR,\n" +
"(SELECT CAST(SUM (A.TRNVLR)AS DECIMAL(18,2)) FROM TRANSACAO A WHERE A.TRNTIP='1' AND A.TRNDAT BETWEEN '"+ relDataIni +"' AND '" + relDataFin +"' AND A.COD_CLIENTE='"+cod_cliente+"')AS TOTAL_PERIODO,\n" +
"A.TRNDAT,\n" +
"A.COD_CLIENTE,\n" +
"A.NOME_CLIENTE,\n" +
"B.PROCOD,\n" +
"B.QUANTIDADE,\n" +
"CAST(SUM (B.ITVVLRTOT)AS DECIMAL(18,2)) as ITVVLRTOT,\n" +
"C.PRODES,\n" +
"D.COD_FINALIZADORA,\n" +
"E.DESCRICAO_FINALIZADORA,\n" +
"F.NOME_FUNCIONARIO\n" +
"\n" +
"FROM TRANSACAO A\n" +
"INNER JOIN\n" +
"ITEVDA B ON\n" +
"A.TRNSEQ =  B.TRNSEQ\n" +
"INNER JOIN  PRODUTO C\n" +
"ON\n" +
"C.PROCOD=B.PROCOD\n" +
"INNER JOIN FINALIZACAO D\n" +
"ON\n" +
"A.TRNSEQ=D.TRNSEQ\n" +
"INNER JOIN FINALIZADORA E\n" +
"ON\n" +
"D.COD_FINALIZADORA=CAST(E.COD_FINALIZADORA AS TEXT)\n" +
"INNER JOIN FUNCIONARIO F\n" +
"ON\n" +
"A.FUNCOD=CAST(F.FUNCOD AS TEXT)\n" +
"WHERE\n" +
"A.TRNTIP='1'\n" +
"AND\n" +
"A.TRNDAT BETWEEN '"+ relDataIni +"' AND '" + relDataFin + "'\n"+
"AND\n" +
"A.COD_CLIENTE='"+cod_cliente+"'\n"+
"GROUP BY A.TRNSEQ, B.PROCOD, B.QUANTIDADE, B.ITVVLRTOT, C.PRODES, D.COD_FINALIZADORA, E.DESCRICAO_FINALIZADORA, F.NOME_FUNCIONARIO ORDER BY A.TRNSEQ DESC" );

                    
          
               //if (conecta.rs.next()){
              //while(conecta.rs.next()){
                  
                  HashMap filtro = new HashMap<>();
                  
               filtro.put("cod_cliente", cod_cliente);                 
               filtro.put("dataIni", sdf.format(relDataIni));
               filtro.put("dataFin", sdf.format(relDataFin));
                 
                  
                  JRResultSetDataSource relatResul = new JRResultSetDataSource(conecta.rs);
                  JasperPrint jpPrint = JasperFillManager.fillReport("relatorios_ireport/RelatorioFiado.jasper",filtro, relatResul);
                  JasperViewer viewer = new JasperViewer(jpPrint, false);
                  viewer.setTitle("Relatório de cliente - Fiado");
                  viewer.setVisible(true);
                  viewer.show();
                  
              
                  
              
          } catch (JRException ex) {
              System.out.println("Erro Relatorio: "+ex);  
         
                Logger.getLogger(Retaguarda.class.getName()).log(Level.SEVERE, null, ex);
                System.out.println("Erro no sql: "+ex);
                
            }
          
     
    }//GEN-LAST:event_jButtonGerarRelatoriosActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                        new HelpCliente().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioVendaPorCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioVendaPorCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonGerarRelatorios;
    private com.toedter.calendar.JDateChooser jDateChooserDataFinal;
    private com.toedter.calendar.JDateChooser jDateChooserDataInicial;
    private javax.swing.JLabel jLabelSelecaoIntervalo;
    private javax.swing.JLabel jLabelSelecaoIntervalo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCod_Cliente;
    // End of variables declaration//GEN-END:variables
}
